# Generated by Django 5.2.4 on 2025-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_name",
            field=models.CharField(default="nomalum", unique=True),
        ),
    ]
