# Generated by Django 5.2.4 on 2025-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room_name",
            field=models.CharField(),
        ),
    ]
