# Generated by Django 5.2.4 on 2025-08-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatersCategory",
            new_name="MastersCategory",
        ),
    ]
