# Generated by Django 5.1.6 on 2025-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('hashPassword', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=254)),
                ('simpleUser', models.BooleanField(default=True)),
            ],
        ),
    ]
