# Generated by Django 5.1.6 on 2025-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hashPassword',
            new_name='Password',
        ),
    ]
