# Generated by Django 5.2.4 on 2025-08-01 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 30 characters or fewer. Letters, digits and @/./+/_ only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w.@+]+$",
                        "Enter a valid username. This value may contain only letters, numbers and @/./+/_ characters.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
